[[repos]]
repo = "local"
hooks = [
    { id = "biome-lint", name = "biome lint", language = "system", entry = "pnpm lint", types_or = ["ts", "tsx", "javascript", "jsx"] },
    { id = "tsc", name = "tsc", language = "system", entry = "pnpm typecheck", types_or = ["ts", "tsx", "javascript", "jsx"], pass_filenames = false },
]
