experimental_monorepo_root = true

[settings]
experimental = true
lockfile = true

[monorepo]
config_roots = [
    "parser",
    "backend",
    "frontend",
]

[tools]
# I need all tools here: mise cannot derive tools from monorepo subdirectories (yet?)
opencode = "1.15.13"
prek = "0.4.3"
# Anything except "latest" breaks lockfile. Some mise bug, I guess.
rust = { version = "latest", profile = "default", components = "llvm-tools" }
uv = "0.11.18"
python = "3.14.5"
node = "24.16.0"
pnpm = "11.20.0"
dprint = "0.54.0"
"aqua:taiki-e/cargo-llvm-cov" = "0.8.7"

[tasks.setup]
description = "Prepare the project"
run = [
    "mise install",
    "prek install --overwrite",
    "mise run parser:build",
    "mise run backend:sync",
    "mise run frontend:sync",
    "cd frontend/ && pnpm exec playwright install",
]

[tasks.config_fmt]
description = "Format config files and docs"
run = "dprint fmt"
