[[repos]]
repo = "local"
hooks = [
    { id = "ruff-format", name = "ruff format", language = "system", entry = "uv run ruff format --exit-non-zero-on-format", types_or = ["python", "pyi"] },
    { id = "ruff-check", name = "ruff check", language = "system", entry = "uv run ruff check --fix", types_or = ["python", "pyi"] },
    { id = "ty-check", name = "ty", language = "system", entry = "uv run ty check", types_or = ["python", "pyi"], pass_filenames = false },
]
