[tasks.fmt]
description = "Format parser code"
run = "cargo fmt"

[tasks.lint]
description = "Lint parser code"
run = "cargo clippy -- -D warnings"

[tasks.test]
description = "Run parser tests"
run = "cargo llvm-cov --fail-under-lines 80 --show-missing-lines"

[tasks.build]
description = "Build parser"
run = "cargo build"

[tasks.run]
description = "Run parser"
run = "cargo run"
